print "Starting maya loading and fbx conversion \n";
	
if (`file -q -exists "/Users/jamaxted-blain/Desktop/GAD402_ImmersiveExperience/Assets/Scenes/Door.mb"`)
{		
	file -o "/Users/jamaxted-blain/Desktop/GAD402_ImmersiveExperience/Assets/Scenes/Door.mb";
	FBXExportEmbeddedTextures -v false;
	// FBXExportHardEdges -v true;
	FBXExportApplyConstantKeyReducer -v false;
	FBXExportShowUI -v false;

	print "Before fbx export\n";
	FBXExport -f "/Users/jamaxted-blain/Desktop/GAD402_ImmersiveExperience/Temp/ExportedFBXFile.fbx";
	print "after fbx export\n";
}
else
	print "Could not open Maya file.";

sysFile -delete "/Users/jamaxted-blain/Desktop/GAD402_ImmersiveExperience/Temp/CommandPipe";

$donepipeKill = `fopen "/Users/jamaxted-blain/Desktop/GAD402_ImmersiveExperience/Temp/SyncPipeKill" "w"`;
fwrite $donepipeKill "Done";
fclose $donepipeKill;
